### ISSUE TITLE
No Zip codes for Puerto Rico? 

### ISSUE THREAD

**Issue by alex-hall** [monterail/zip-codes#12]
According to: [this article](https://en.wikipedia.org/wiki/Postal_codes_in_Puerto_Rico) Puerto Rico has US zip codes between the range of ``` 00600 to 00799 and 00900 to 00999```.

Would a pull request be accepted for this range? I'm not sure how you would derive the city for each zip code but the state code, state name, and time zone could all be provided.

**Comment by alex-hall** [comment]
Also missing Guam FYI. I can add those 10 as well.

**Comment by alex-hall** [comment]
#13

**Comment by niyando** [comment]
Could we please have this merged?

**Comment by alex-hall** [comment]
For what it's worth I have the branch on my repo...

**Comment by niyando** [comment]
Yes, I am planning to refer the same in my gemfile until this gets merged. Thanks for the contribution.

**Comment by phensalves** [comment]
zipcodes for Brazil?

**Comment by alex-hall** [comment]
Is there a decent source for this? I don't mind updating my version of the
gem.

**Comment by brodyhoskins** [comment]
#28
