### ISSUE TITLE
Hand over development/Gem ownership

### ISSUE THREAD

**Issue by chytreg** [monterail/zip-codes#23]
We are willing to hand over the development and gem ownership, would you like to take care of this gem?

cc @hwhelchel @alex-hall @pellejacobs @bartes @skippy @libruce @markprzepiora @clarkras @jswilliam93 @Chester929

**Comment by brodyhoskins** [comment]
Hello @chytreg, I have a forked version of this [here](https://github.com/next-tms/zip-codes). I'm interested in any work you or your team have done.

I've been considering releasing a new gem based on this. Do you have any additions that we could collaborate on?

CC @hwhelchel @alex-hall @pellejacobs @bartes @skippy @libruce @markprzepiora @clarkras @jswilliam93 @Chester929
